apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: persistent-storage
      mountPath: /tmp
    - name: node3-storage
      mountPath: /mnt/polkadot3
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-pv
  - name: node3-storage
    persistentVolumeClaim:
      claimName: efs-node3-storage