apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: efs-public-rpc-storage
      mountPath: /mnt/public-node
  volumes:
  - name: efs-public-rpc-storage
    persistentVolumeClaim:
      claimName: efs-public-rpc-storage