apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: node3-storage
      mountPath: /mnt/polkadot3
    - name: node4-storage
      mountPath: /mnt/polkadot4 
  volumes:
  - name: node3-storage
    persistentVolumeClaim:
      claimName: efs-node3-storage
  - name: node4-storage
    persistentVolumeClaim:
      claimName: efs-node4-storage    