apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basiliskapivol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests: 
      storage: 40Gi


