apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: indexer
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: indexer
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn db:bootstrap && yarn start:prod
          env:
            - name: BLOCK_HEIGHT
              value: "0"
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: indexer
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: INDEXER_WORKERS
              value: "5"
            - name: REDIS_URI
              value: redis://redis:6379/0
            - name: TYPES_ALIAS
              value: typesAlias.json
            - name: TYPES_JSON
              value: types.json
            - name: WS_PROVIDER_ENDPOINT_URI
              value: ws://parachain-testnet.hydration.cloud/ws/
          image: subsquid/hydra-indexer:4
          name: indexer
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: persistent-storage
      restartPolicy: Always
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-pv
status: {}
