apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hydra-ui-test
  name: indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: indexer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: indexer
    spec:
      containers:
        - args:
            - sh
            - -c
            - yarn db:bootstrap && yarn start:prod
          env:
            - name: BLOCK_HEIGHT
              value: "0"
            - name: DB_HOST
              value: 192.168.177.121
            - name: DB_NAME
              value: indexer
            - name: DB_PASS
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: INDEXER_WORKERS
              value: "5"
            - name: REDIS_URI
              value: redis://192.168.133.12:6379
            - name: TYPES_ALIAS
              value: /tmp/typesAlias.json
            - name: TYPES_JSON
              value: /tmp/types.json
            - name: WS_PROVIDER_ENDPOINT_URI
              value: wss://parachain-testnet.hydration.cloud/ws/
          image: subsquid/hydra-indexer:4
          name: indexer
          resources: {}
          volumeMounts:
            - mountPath: /tmp
              name: persistent-storage
      restartPolicy: Always
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-pv
status: {}
