apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hydraindexervol 
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 30Gi
---
