apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresvol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
---
