apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod-1
spec:
  containers:
  - name: cleanup-pod-1
    image: redis
    command: ["/bin/sh", "-c"]
    args: 
      - rm -rf /mnt/public-node/chains/
        rm -rf /mnt/polkadot1/chains/
    volumeMounts:
    - name: efs-public-rpc-storage
      mountPath: /mnt/public-node
    - name: node1-storage
      mountPath: /mnt/polkadot1 
  volumes:
  - name: efs-public-rpc-storage
    persistentVolumeClaim:
      claimName: efs-public-rpc-storage
  - name: node1-storage
    persistentVolumeClaim:
      claimName: efs-node1-storage 