apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod-9
spec:
  containers:
  - name: cleanup-pod-9
    image: redis
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: statemine-public-node-storage
      mountPath: /mnt/statemine-public-node
  volumes:
  - name: statemine-public-node-storage
    persistentVolumeClaim:
      claimName: statemine-public-claim
