apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod-7
spec:
  containers:
  - name: cleanup-pod-7
    image: redis
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: basilisk3-storage
      mountPath: /mnt/basilisk3
    - name: basilisk-public-node-storage
      mountPath: /mnt/basilisk-public-node
  volumes:
  - name: basilisk3-storage
    persistentVolumeClaim:
      claimName: basilisk3-claim
  - name: basilisk-public-node-storage
    persistentVolumeClaim:
      claimName: basilisk-public-claim