apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod-4
spec:
  containers:
  - name: cleanup-pod-4
    image: redis
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: node6-storage
      mountPath: /mnt/polkadot6
    - name: node7-storage
      mountPath: /mnt/polkadot7
  volumes:
  - name: node6-storage
    persistentVolumeClaim:
      claimName: node6-claim
  - name: node7-storage
    persistentVolumeClaim:
      claimName: node7-claim   