apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodes-config-volume
  namespace: default
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04ddac5f8e46515b9
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodes-config-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi
---