apiVersion: v1
kind: Pod
metadata:
  name: copy-pod
spec:
  containers:
  - name: copy-pod
    image: redis
    command: ["sh", "-c", "tail -f /dev/null"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /tmp
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-pv