name: Deploy on Kubernetes Cluster
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [run-k8s-deployment]
jobs:
  run-k8s-deployment:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_K8S_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_K8S_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
      - name: Sleep for 10 seconds
        run: sleep 10
      - name: Configure AWS CLI and K8s
        run: |
          sudo apt-get install awscli
          aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}; aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}; aws configure set default.region eu-west-1
      - name: Configure K8S Cluster
        run: aws eks --region eu-west-1 update-kubeconfig --name hydradx-c
      - name: Delete deployments
        run: kubectl delete --all deployments --namespace=hydra-ui-test
      - name: Create cleanup pods
        working-directory: ./public-testnet
        run: kubectl apply $(ls cleanup*.yaml | awk ' { print " -f " $1 } ') -n hydra-ui-test
      - name: Cleanup volumes
        run: |
          kubectl config set-context --current --namespace=hydra-ui-test
          kubectl exec cleanup-pod-1 -- bash -c "[ -d /mnt/public-node/chains ] rm -rf /mnt/public-node/chains"
          kubectl exec cleanup-pod-1 -- bash -c "[ -d /mnt/polkadot1/chains ] rm -rf /mnt/polkadot1/chains"
          kubectl exec cleanup-pod-2 -- bash -c "[ -d /mnt/polkadot2/chains ] rm -rf /mnt/polkadot2/chains"
          kubectl exec cleanup-pod-2 -- bash -c "[ -d /mnt/polkadot3/chains ] rm -rf /mnt/polkadot3/chains"
          kubectl exec cleanup-pod-3 -- bash -c "[ -d /mnt/polkadot4/chains ] rm -rf /mnt/polkadot4/chains"
          kubectl exec cleanup-pod-3 -- bash -c "[ -d /mnt/polkadot5/chains ] rm -rf /mnt/polkadot5/chains"
          kubectl exec cleanup-pod-4 -- bash -c "[ -d /mnt/polkadot6/chains ] rm -rf /mnt/polkadot6/chains"
          kubectl exec cleanup-pod-4 -- bash -c "[ -d /mnt/polkadot7/chains ] rm -rf /mnt/polkadot7/chains"
          kubectl exec cleanup-pod-5 -- bash -c "[ -d /mnt/polkadot8/chains ] rm -rf /mnt/polkadot8/chains"
          
          
